---
dist: xenial   # required for Python >= 3.7
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install .
script: pytest --full-trace -lk 'not integration'
jobs:
  include:
    - stage: integration test
      python: 3.4
      script: pytest --full-trace -lv
    - python: 3.8-dev
      script: pytest --full-trace -lv
    - stage: deploy
      python: 3.6
      deploy:
        provider: pypi
        user: johnpaton
        password: $PYPI_PASSWORD
        on:
          branch: master
          tags: true
