---
dist: bionic
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -U pip
  - pip install -e .[format,lint,test]
script: pytest -ra -q --cov --cov-append -m "not integration"
jobs:
  include:
    - stage: integration
      python: 3.8
      script: pytest -ra -q --cov --cov-append -m "integration"
    - stage: lint
      python: 3.8
      script:
        - black --check .
        - isort --check .
        - mypy --strict airbase/
        - mypy tests/
    - stage: deploy
      python: 3.8
      script: skip
      deploy:
        provider: pypi
        user: johnpaton
        password: $PYPI_PASSWORD
        on:
          tags: true
stages:
  - test
  - integration
  - lint
  - deploy
