---
language: python
install:
  - pip install .
script:
  - echo "skipping tests"
matrix:
  include:
    - python: 3.6
      deploy:
        provider: pypi
        user: johnpaton
        password: $PYPI_PASSWORD
        on:
          branch: master
          tags: true
