---
dist: bionic
language: python
python:
  - 3.7
  - 3.8
  - 3.9
install:
  - pip install -U pip
  - pip install -U tox tox-travis
jobs:
  include:
    - stage: test
      script: tox -e py -- -m "not integration" --cov --cov-append
    - stage: integration
      python: 3.8
      script: tox -e py -- -m "integration" --cov --cov-append
    - stage: lint
      python: 3.8
      script:
        - tox -e format
        - tox -e lint
    - stage: deploy
      python: 3.8
      script: skip
      deploy:
        provider: pypi
        user: johnpaton
        password: $PYPI_PASSWORD
        on:
          tags: true
stages:
  - lint
  - test
  - integration
  - deploy
