---
dist: xenial   # required for Python >= 3.7
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install -r requirements-test.txt
  - pip install .
script: pytest -lk "not integration" --cov-append --cov=airbase --cov-report=xml --cov-report=term
jobs:
  include:
    - stage: lint
      python: 3.6
      install: pip install black
      script: black --check .
    - stage: integration
      python: 3.5
      script: pytest -lvk "integration" --cov-append --cov=airbase --cov-report=xml --cov-report=term
    - python: 3.9
      script: pytest -lvk "integration" --cov-append --cov=airbase --cov-report=xml --cov-report=term
    - stage: deploy
      python: 3.6
      script: skip
      deploy:
        provider: pypi
        user: johnpaton
        password: $PYPI_PASSWORD
        on:
          tags: true
stages:
  - lint
  - test
  - integration
  - deploy
