---
dist: xenial   # required for Python >= 3.7
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest -lvk 'not integration'
jobs:
  include:
    - stage: lint
      python: 3.6
      install: pip install black
      script: black --check .
    - stage: integration
      python: 3.4
      script: pytest -lvk integration
    - python: 3.8-dev
      script: pytest -lvk integration
    - stage: deploy
      python: 3.6
      script: skip
      deploy:
        provider: pypi
        user: johnpaton
        password: $PYPI_PASSWORD
        on:
          branch: master
          tags: true
stages:
  - lint
  - test
  - integration
  - name: deploy
    if: branch = master
