[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--showlocals"
testpaths = ["tests"]

[tool.coverage.run]
source = ["airbase"]

[tool.coverage.report]
skip_covered = true
skip_empty = true
show_missing = true

[tool.black]
line-length = 80
target-version = ["py37"]

[tool.isort]
line_length = 80
py_version = "37"
profile = "black"
src_paths = ["airbase", "tests"]
extend_skip = ["scripts"]

[tool.mypy]
warn_unused_configs = true
warn_unused_ignores = false
warn_no_return = true
warn_return_any = true
warn_unreachable = true
show_error_codes = true
pretty = true
sqlite_cache = true
exclude = "docs|scripts"

[[tool.mypy.overrides]]
module = ["tqdm"]
ignore_missing_imports = true

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37, py38, py39, py310, py311, lint, docs, integration
skip_missing_interpreters = True
isolated_build = True

[testenv]
commands_pre =
    python --version
commands =
    pytest -ra -q {posargs:--cov -k "not integration"}
extras = 
    test

[testenv:integration]
commands_pre =
    python --version
commands =
    pytest -ra -q {posargs:--cov -k integration}
extras = 
    test

[testenv:lint]
skipsdist=True
commands =
    pre-commit run --all-files --show-diff-on-failure
deps =
    pre-commit

[testenv:docs]
skipsdist=True
commands =
    sphinx-build {posargs:-M html} docs/source docs/build
extras = 
    docs
"""
