[tool.pytest.ini_options]
minversion = "6.0"
required_plugins = "pytest-responses pytest-mock pytest-cov"
addopts = "--showlocals --cov --cov-report=html --cov-report=term"
testpaths = ["tests"]

[tool.coverage.run]
source = ["airbase"]

[tool.coverage.report]
skip_covered = true
skip_empty = true
show_missing= true

[tool.black]
line-length = 80
target-version = ["py37"]
