[tool.pytest.ini_options]
minversion = "6.0"
required_plugins = "pytest-responses pytest-mock pytest-cov"
addopts = "--showlocals --cov --cov-report=html --cov-report=term"
testpaths = ["tests"]

[tool.coverage.run]
source = ["airbase"]

[tool.coverage.report]
skip_covered = true
skip_empty = true
show_missing= true

[tool.black]
line-length = 80
target-version = ["py37"]

[tool.isort]
line_length = 80
py_version = "37"
profile = "black"
src_paths = ["airbase", "tests"]
extend_skip = ["scripts"]
