[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
required_plugins = "pytest-asyncio"
addopts = "--showlocals"
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.coverage.run]
source = ["airbase"]

[tool.coverage.report]
skip_covered = true
skip_empty = true
show_missing= true

[tool.black]
line-length = 80
target-version = ["py37"]

[tool.isort]
line_length = 80
py_version = "37"
profile = "black"
src_paths = ["airbase", "tests"]
extend_skip = ["scripts"]

[tool.mypy]
python_version = "3.7"
warn_unused_configs = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = false
warn_unreachable = true
show_error_codes = true
pretty = true
sqlite_cache = true
exclude = "docs|scripts"

[[tool.mypy.overrides]]
module = ["tqdm"]
ignore_missing_imports = true

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37, py38, py39, py310, format, lint, docs
skip_missing_interpreters = True
isolated_build = True

[testenv]
commands_pre =
    python --version
commands =
    pytest -ra -q {posargs:--cov}
extras = 
    test

[testenv:format]
skipsdist=True
commands =
    black --check .
    isort --check .
extras = 
    format

[testenv:lint]
skipsdist=True
commands =
    mypy .
extras =
    test
    lint

[testenv:docs]
skipsdist=True
commands =
    make -C docs html
extras = 
    docs
"""
