[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
required_plugins = "pytest-responses pytest-mock pytest-cov"
addopts = "--showlocals --cov --cov-report=html --cov-report=term"
testpaths = ["tests"]

[tool.coverage.run]
source = ["airbase"]

[tool.coverage.report]
skip_covered = true
skip_empty = true
show_missing= true

[tool.black]
line-length = 80
target-version = ["py37"]

[tool.isort]
line_length = 80
py_version = "37"
profile = "black"
src_paths = ["airbase", "tests"]
extend_skip = ["scripts"]

[tool.mypy]
python_version = "3.7"
install_types = true
warn_unused_configs = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = false
warn_unreachable = true
show_error_codes = true
pretty = true
sqlite_cache = true
exclude = "docs"

[[tool.mypy.overrides]]
module = ["setuptools", "tqdm"]
ignore_missing_imports = true
