COUNTRY_CODES = set(
    """
    AD AL AT BA BE BG CH CY CZ DE DK EE ES FI FR GB GI GR HR HU
    IE IS IT LI LT LU LV ME MK MT NL NO PL PT RO RS SE SI SK TR
    XK
    """.split()
)


POLLUTANT_NOTATIONS = {
    "(CH3)2-CH-CH2-CH2-CH3",
    "(CH3)3-C-CH2-CH-(CH3)2",
    "1,1,1-trichloroethane (air)",
    "1,1,2-trichloroethane (air)",
    "1,1-dichloroethane (air)",
    "1,2,3-C6H3(CH3)3",
    "1,2,4-C6H3(CH3)3",
    "1,2-dichloroethane (air)",
    "1,2-dichloroethylene (air)",
    "1,3,5-C6H3(CH3)3",
    "1-Methyl Naphthalene",
    "1-Methyl anthracene",
    "1-Methyl anthracene in PM10",
    "1-Methyl phenanthrene",
    "1-methylnaphtalene",
    "1-methylphenanthrene",
    "2-Methyl Naphthalene",
    "2-Methyl anthracene",
    "2-Methyl phenanthrene",
    "2-methylanthracene",
    "2-methylbenzaldehyde",
    "2-methylnaphtalene",
    "2-methylphenanthrene",
    "3-methylbenzaldehyde",
    "3-methylpentane",
    "3-methylphenantrene",
    "4-methylbenzaldehyde",
    "4.5-Methylene phenanthrene",
    "4.5-Methylene phenanthrene in PM10",
    "5-Methyl Chrysene",
    "5-Methyl Chrysene in PM10",
    "6:2-FTS",
    "9-Methyl anthracene",
    "9-Methyl anthracene in PM10",
    "9-methylphenantrene",
    "Acenaphthene",
    "Acenaphthylene",
    "Acenaphtylene",
    "Acetaldehyde",
    "Acetone",
    "Acetone + Acrolein",
    "Acetophenone",
    "Acroleine",
    "Al",
    "Aldrin",
    "Anthanthrene",
    "Anthanthrene in PM10",
    "Anthracene",
    "Anthracene in PM10 (aerosol)",
    "Anti-DP",
    "Aromatics (except C6H6)",
    "As",
    "As in PM10",
    "As in PM2.5",
    "As in TSP",
    "Atrazine",
    "BDE100",
    "BDE153",
    "BDE154",
    "BDE209",
    "BDE47",
    "BDE85",
    "BDE99",
    "BEH-TEBP",
    "BS",
    "BTBPT",
    "BaP",
    "BaP in PM10",
    "BaP in PM2.5",
    "Back scattering",
    "Benzaldehyde",
    "Benzo(a)anthracene",
    "Benzo(a)anthracene in PM10",
    "Benzo(a)anthracene in PM2.5",
    "Benzo(a)fluoranthene",
    "Benzo(a)fluorene",
    "Benzo(b)fluoranthene",
    "Benzo(b)fluoranthene in PM10",
    "Benzo(b)fluoranthene in PM2.5",
    "Benzo(b)fluorene",
    "Benzo(b)naphtho(2,1-d)thiophene",
    "Benzo(b)naphtho(2,1-d)thiophene in PM10",
    "Benzo(b+j)fluoranthene",
    "Benzo(b+j)fluoranthene in PM10",
    "Benzo(b+j+k)fluoranthenes",
    "Benzo(b,j)fluorantheneinPM10",
    "Benzo(b,j,k)fluoranthene",
    "Benzo(b,j,k)fluorantheneInPM1",
    "Benzo(c)phenanthrene",
    "Benzo(c)phenanthrene in PM10",
    "Benzo(e)pyrene",
    "Benzo(e)pyrene in PM10",
    "Benzo(ghi)fluoranthene",
    "Benzo(ghi)perylene",
    "Benzo(ghi)perylene in PM10",
    "Benzo(j)fluoranthene",
    "Benzo(j)fluoranthene in PM10",
    "Benzo(j)fluoranthene in PM2.5",
    "Benzo(j)fluorene",
    "Benzo(k)fluoranthene",
    "Benzo(k)fluoranthene in PM10",
    "Benzo(k)fluoranthene in PM2.5",
    "Benzo(k+j)fluoranthene",
    "Benzo(k+j)fluoranthene in PM10",
    "Biphenyl",
    "Black Carbon",
    "Butanales",
    "Butenes",
    "C2Cl4",
    "C2H6",
    "C6H12",
    "C6H12O2",
    "C6H14",
    "C6H4-(CH3)2",
    "C6H4Cl2",
    "C6H5-C2H5",
    "C6H5-CH3",
    "C6H5-CH=CH2",
    "C6H6",
    "C7H16",
    "C8H18",
    "C8H8O",
    "C9H12",
    "C9H20",
    "CDD1N",
    "CDD4X",
    "CDD6P",
    "CDD6X",
    "CDD9X",
    "CDDO",
    "CDF2N",
    "CDF2T",
    "CDF4X",
    "CDF6P",
    "CDF6X",
    "CDF9P",
    "CDF9X",
    "CDFDN",
    "CDFDX",
    "CDFO",
    "CDFP2",
    "CDFX1",
    "CFC-11",
    "CFC-113",
    "CFC-12",
    "CH2=CH-C(CH3)=CH2",
    "CH2=CH-CH3",
    "CH2=CH-CH3 + H3C-CH2-CH2-CH3",
    "CH2=CH-CH=CH2",
    "CH2=CH-CN",
    "CH2Cl2",
    "CH4",
    "CHCl=CCl2",
    "CO",
    "CO2",
    "CS2",
    "Ca++",
    "Ca2+ in PM10",
    "Ca2+ in PM2.5",
    "Carbon-tetrachloride",
    "Cd",
    "Cd in PM10",
    "Cd in PM2.5",
    "Cd in TSP",
    "Chlorinated hydrocarbons",
    "Chlorobenzene (air)",
    "Cholanthrene",
    "Cholanthrene in PM10",
    "Chrysene",
    "Chrysene + Triphenylene",
    "Chrysene in PM10",
    "Cl-",
    "Cl- in PM10",
    "Cl- in PM2.5",
    "Cl- in TSP",
    "Co",
    "Co in PM10",
    "Co in PM2.5",
    "Coronene",
    "Coronene in PM10",
    "Cr",
    "Cr in PM10",
    "Cr in PM2.5",
    "Cr in TSP",
    "Crotonaldehyde",
    "Cu",
    "Cu in PM10",
    "Cu in PM2.5",
    "Cu in TSP",
    "Cyclo-hexane",
    "Cyclopenta(c,d)pyrene",
    "Cyclopenta(c,d)pyrene in PM10",
    "Cyklopenta(cd)pyrene",
    "DBDPE",
    "DCMU",
    "Dibenz(ac+ah)anthracenes",
    "Dibenz(ah)anthracene",
    "Dibenzo(ac)anthracene",
    "Dibenzo(ac)anthracene in PM10",
    "Dibenzo(ac+ah)anthracene in PM10",
    "Dibenzo(ac+ah)anthracenes",
    "Dibenzo(ae)pyrene",
    "Dibenzo(ae)pyrene in PM10",
    "Dibenzo(ah)anthracene",
    "Dibenzo(ah)anthracene in PM10",
    "Dibenzo(ah)anthracene in PM2.5",
    "Dibenzo(ah)pyrene",
    "Dibenzo(ah)pyrene in PM10",
    "Dibenzo(ah+ac)anthracene",
    "Dibenzo(ah+ac)anthracene in PM10",
    "Dibenzo(ai)pyrene",
    "Dibenzo(ai)pyrene in PM10",
    "Dibenzo(al)pyrene",
    "Dibenzo(al)pyrene in PM10",
    "Dibenzofuran",
    "Dibenzothiophene",
    "Dieldrin",
    "EC",
    "EC in PM10",
    "EC in PM2.5",
    "EH-TBB",
    "Endosulfan sulfate",
    "Endrin",
    "Fe",
    "Fe in PM10",
    "Fe in PM2.5",
    "Fluor (except HF)",
    "Fluoranthene",
    "Fluoranthene in PM10 (aerosol)",
    "Fluorene",
    "Glyoxal",
    "H+",
    "H2C=CH-CH2-CH2-CH3",
    "H2C=CH-CH2-CH3",
    "H2C=CH2",
    "H2S",
    "H3C-(CH2)3-CH3",
    "H3C-(CH2)3-CH3 + H3C-CH2-CH(CH3)2",
    "H3C-CH(CH3)2",
    "H3C-CH2-CH(CH3)2",
    "H3C-CH2-CH2-CH3",
    "H3C-CH2-CH3",
    "H3C-HC=CH-CH2-CH3",
    "HBB",
    "HBCD",
    "HC > C6 (excl. AROM. & CHLH)",
    "HC C2-C6(excl. AROM. & CHLH)",
    "HC=CH",
    "HCB",
    "HCFC-123",
    "HCFC-22",
    "HCHO",
    "HCl",
    "HF",
    "HNO3",
    "HNO3+NO3",
    "Halon 1211",
    "Halon 1301",
    "Heptachlor",
    "Heptachlor Epoxide",
    "Hg",
    "Hg in PM10",
    "Hg in PM2.5",
    "Hg in TSP",
    "Hg-reactive",
    "Hg0",
    "Hg0 + Hg-reactive",
    "Indeno-(1,2,3-cd)pyrene",
    "Indeno-(1,2,3-cd)pyrene in PM",
    "Indeno-(1,2,3-cd)pyrene in PM2",
    "Isoproturon",
    "K+",
    "K+ in PM10",
    "K+ in PM2.5",
    "Kj-N",
    "MCCP",
    "Methacroleine",
    "Methacroleine + Butanal",
    "Methyl-chloroform",
    "Methyletylketone (MEK)",
    "Methylglyoxal",
    "Methylvinylketone (MVK)",
    "Mg++",
    "Mg2+ in PM10",
    "Mg2+ in PM2.5",
    "Mn",
    "Mn in PM10",
    "Mn in PM2.5",
    "Mn in TSP",
    "Mo",
    "N-DEP",
    "N2O",
    "NH3",
    "NH3+NH4",
    "NH4",
    "NH4+",
    "NH4+ in PM10",
    "NH4+ in PM2.5",
    "NO",
    "NO2",
    "NO3",
    "NO3-",
    "NO3- in PM10",
    "NO3- in PM2.5",
    "NOX as NO2",
    "NOy",
    "NT",
    "NVPM1",
    "NVPM10",
    "NVPM2.5",
    "Na+",
    "Na+  in PM10",
    "Na+  in PM2.5",
    "Na+  in TSP",
    "Naphtalene",
    "Naphthalene",
    "Neo-hexane",
    "Neo-pentane",
    "Ni",
    "Ni in PM10",
    "Ni in PM2.5",
    "Ni in TSP",
    "O3",
    "OC",
    "OC in PM10",
    "OC in PM2.5",
    "PAH",
    "PAN",
    "PBEB",
    "PBT",
    "PCB-101",
    "PCB-105",
    "PCB-114",
    "PCB-118",
    "PCB-128",
    "PCB-138",
    "PCB-141",
    "PCB-149",
    "PCB-153",
    "PCB-156",
    "PCB-157",
    "PCB-167",
    "PCB-170",
    "PCB-177",
    "PCB-18",
    "PCB-180",
    "PCB-183",
    "PCB-187",
    "PCB-189",
    "PCB-194",
    "PCB-206",
    "PCB-209",
    "PCB-26",
    "PCB-28",
    "PCB-31",
    "PCB-33",
    "PCB-37",
    "PCB-44",
    "PCB-47",
    "PCB-52",
    "PCB-60",
    "PCB-66",
    "PCB-74",
    "PCB-99",
    "PCB_122",
    "PCB_123",
    "PCB_128",
    "PCB_138",
    "PFBA",
    "PFBS",
    "PFDA",
    "PFDS",
    "PFHpA",
    "PFHxA",
    "PFHxS",
    "PFNA",
    "PFOA",
    "PFOS",
    "PFOSA",
    "PFPeA",
    "PFUnDA",
    "PM1",
    "PM10",
    "PM2.5",
    "PO43-",
    "Pb",
    "Pb in PM10",
    "Pb in PM2.5",
    "Pb in TSP",
    "Pentenes",
    "Perylene",
    "Perylene in PM10",
    "Phenanthrene",
    "Phenanthrene in PM10 (aerosol)",
    "Propanal",
    "Pyrene",
    "Pyrene in PM10 (aerosol)",
    "Radioactivity",
    "Retene",
    "S-DEP",
    "SA",
    "SCCP",
    "SO2",
    "SO2 + SO4--",
    "SO4 (H2SO4 aerosols) (SO4--)",
    "SO4--",
    "SO4-- corr",
    "SO42-  in PM10",
    "SO42- in PM2.5",
    "SPM",
    "Se",
    "Se in PM10",
    "Se in PM2.5",
    "Sn in PM10",
    "Syn-DP",
    "T-VOC",
    "TBP",
    "TCDD",
    "THC (NM)",
    "TI",
    "TP",
    "Tetrachloromethane (air)",
    "UFPs",
    "V",
    "V in PM10",
    "V in PM2.5",
    "VC",
    "VPM1",
    "VPM10",
    "VPM2.5",
    "Valeraldehyde",
    "Vanadium",
    "Zn",
    "Zn in PM10",
    "Zn in PM2.5",
    "Zn in TSP",
    "alpha-Endosulfan",
    "alpha-HCH",
    "beta-Endosulfan",
    "beta-HCH",
    "cis-CD",
    "cis-H3C-CH=CH-CH3",
    "cis-H3C-HC=CH-CH2-CH3",
    "cis-NO",
    "gamma-HCH",
    "i-Heptane",
    "k",
    "m,p-C6H4(CH3)2",
    "m-C6H4-(CH3)2",
    "n-Hexanal",
    "o,p'-DDD",
    "o,p'-DDE",
    "o,p'-DDT",
    "o-C6H4-(CH3)2",
    "p,p'-DDD",
    "p,p'-DDE",
    "p,p'-DDT",
    "p-C6H4(CH3)2",
    "pH",
    "precip_amount",
    "precip_amount_off",
    "sum-PCB",
    "trans-CD",
    "trans-H3C-CH=CH-CH3",
    "trans-H3C-HC=CH-CH2-CH3",
    "trans-NO",
    "trans_NO",
    "α-DBE-DBCH",
    "β-DBE-DBCH",
}
