name: CI/CD
on:
  push:
  schedule:
    - cron:  '0 12 1 * *'  # On the first day of the month
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: |
          pip install .[test]
      - run: |
          pytest -lk "not integration" --cov

  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install .[test]
      - run: |
          pytest -lvk "integration"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  build-and-deploy:
    needs: [unit-test, integration-test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install build
      - run: |
          python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: |
          github.repository == 'JohnPaton/airbase' &&
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
